In [1]:
import modern_robotics as mr

In [2]:
dir(mr)

['Adjoint',
 'AxisAng3',
 'AxisAng6',
 'CartesianTrajectory',
 'ComputedTorque',
 'CubicTimeScaling',
 'DistanceToSE3',
 'DistanceToSO3',
 'EndEffectorForces',
 'EulerStep',
 'FKinBody',
 'FKinSpace',
 'ForwardDynamics',
 'ForwardDynamicsTrajectory',
 'GravityForces',
 'IKinBody',
 'IKinSpace',
 'InverseDynamics',
 'InverseDynamicsTrajectory',
 'JacobianBody',
 'JacobianSpace',
 'JointTrajectory',
 'MassMatrix',
 'MatrixExp3',
 'MatrixExp6',
 'MatrixLog3',
 'MatrixLog6',
 'NearZero',
 'Normalize',
 'ProjectToSE3',
 'ProjectToSO3',
 'QuinticTimeScaling',
 'RotInv',
 'RpToTrans',
 'ScrewToAxis',
 'ScrewTrajectory',
 'SimulateControl',
 'TestIfSE3',
 'TestIfSO3',
 'TransInv',
 'TransToRp',
 'VecTose3',
 'VecToso3',
 'VelQuadraticForces',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'ad',
 'core',
 'np',
 'print_function',
 'se3ToVec',
 'so3ToVec']

In [3]:
import robopy as rp

In [4]:
dir(rp)

['Orion5',
 'Puma560',
 'Quaternion',
 'Revolute',
 'SE2',
 'SE3',
 'SO2',
 'SO3',
 'SerialLink',
 'SuperPose',
 'UnitQuaternion',
 'VtkPipeline',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'angvec2r',
 'angvec2tr',
 'axesActor2d',
 'axesCube',
 'axesCubeFloor',
 'axesUniversal',
 'axes_x_y',
 'base',
 'check_args',
 'common',
 'ctraj',
 'eul2r',
 'eul2tr',
 'expm',
 'floor',
 'graphics',
 'ishomog',
 'isvec',
 'lspb',
 'math',
 'matrices_equal',
 'matrix_mismatch_string_builder',
 'model',
 'np',
 'np2vtk',
 'npt',
 'oa2r',
 'oa2tr',
 'pi',
 'pkg_resources',
 'pose',
 'print_function',
 'quaternion',
 'r2t',
 'randint',
 'rot2',
 'rotx',
 'roty',
 'rotz',
 'rpy2r',
 'rpy2tr',
 'rt2tr',
 'serial_link',
 'skew',
 'skewa',
 'sqrt',
 'super_pose',
 't2r',
 'test_transforms',
 'tests',
 'tr',
 'tr2angvec',
 'tr2eul',
 'tr2rpy',
 'tr2rt',
 'trace',
 'transforms',
 'transl',
 'transl2',
 'trexp',
 'trexp2',


In [5]:
import numpy as np

In [6]:
R1 = rp.rotx(90,'deg')

In [7]:
print(R1)

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


In [8]:
R2 = rp.rotz(180,'deg')

In [9]:
print(R2)

[[-1. -0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]


In [10]:
R1*R2

matrix([[-1.,  0.,  0.],
        [ 0.,  0., -1.],
        [ 0., -1.,  0.]])